"""rename_signature_path_to_signature_data

Revision ID: 838c6b4ac1a2
Revises: 0a0af3edcf66
Create Date: 2026-02-21 23:44:09.314105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838c6b4ac1a2'
down_revision: Union[str, None] = '0a0af3edcf66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_requests', sa.Column('signature_data', sa.Text(), nullable=True))
    op.drop_column('certificate_requests', 'signature_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_requests', sa.Column('signature_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('certificate_requests', 'signature_data')
    # ### end Alembic commands ###
