"""add major column to programs

Revision ID: 9b967c8c55a0
Revises: c88d702138bd
Create Date: 2026-03-02 20:03:40.853433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b967c8c55a0'
down_revision: Union[str, None] = 'c88d702138bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('major', sa.String(length=255), nullable=True))
    op.add_column('programs', sa.Column('college_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'programs', 'colleges', ['college_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.drop_column('programs', 'college_id')
    op.drop_column('programs', 'major')
    # ### end Alembic commands ###
