"""add major column to programs

Revision ID: 9b967c8c55a0
Revises: c88d702138bd
Create Date: 2026-03-02 20:03:40.853433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '9b967c8c55a0'
down_revision: Union[str, None] = 'c88d702138bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {col["name"] for col in inspector.get_columns("programs")}
    if "major" not in columns:
        op.add_column(
            "programs",
            sa.Column("major", sa.String(length=255), nullable=True),
        )
    if "college_id" not in columns:
        op.add_column("programs", sa.Column("college_id", sa.Integer(), nullable=False))
    fks = {fk["name"] for fk in inspector.get_foreign_keys("programs")}
    if None not in fks and "programs_college_id_fkey" not in fks:
        op.create_foreign_key(None, "programs", "colleges", ["college_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    fks = {fk["name"] for fk in inspector.get_foreign_keys("programs")}
    if None in fks or "programs_college_id_fkey" in fks:
        op.drop_constraint(None, "programs", type_="foreignkey")
    columns = {col["name"] for col in inspector.get_columns("programs")}
    if "college_id" in columns:
        op.drop_column("programs", "college_id")
    if "major" in columns:
        op.drop_column("programs", "major")
    # ### end Alembic commands ###
