"""add colleges campuses and refactor program student

Revision ID: c88d702138bd
Revises: 838c6b4ac1a2
Create Date: 2026-03-02 19:54:01.761350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88d702138bd'
down_revision: Union[str, None] = '838c6b4ac1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signatures_id', table_name='signatures')
    op.drop_table('signatures')
    op.add_column('campuses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('campuses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('campuses', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('colleges', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('colleges', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('colleges', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('colleges', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'colleges', ['code'])
    op.add_column('programs', sa.Column('campus_id', sa.Integer(), nullable=False))
    op.drop_constraint('programs_name_key', 'programs', type_='unique')
    op.create_foreign_key(None, 'programs', 'campuses', ['campus_id'], ['id'])
    op.add_column('students', sa.Column('program_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'programs', ['program_id'], ['id'])
    op.drop_column('students', 'program')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('program', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'program_id')
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_unique_constraint('programs_name_key', 'programs', ['name'])
    op.drop_column('programs', 'campus_id')
    op.drop_constraint(None, 'colleges', type_='unique')
    op.alter_column('colleges', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('colleges', 'updated_at')
    op.drop_column('colleges', 'created_at')
    op.drop_column('colleges', 'code')
    op.alter_column('campuses', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('campuses', 'updated_at')
    op.drop_column('campuses', 'created_at')
    op.create_table('signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signatures_pkey')
    )
    op.create_index('ix_signatures_id', 'signatures', ['id'], unique=False)
    # ### end Alembic commands ###
