"""add colleges campuses and refactor program student

Revision ID: c88d702138bd
Revises: 838c6b4ac1a2
Create Date: 2026-03-02 19:54:01.761350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c88d702138bd'
down_revision: Union[str, None] = '838c6b4ac1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    if "signatures" in inspector.get_table_names():
        indexes = {idx["name"] for idx in inspector.get_indexes("signatures")}
        if "ix_signatures_id" in indexes:
            op.drop_index("ix_signatures_id", table_name="signatures")
        op.drop_table("signatures")
    campuses_cols = {col["name"]: col for col in inspector.get_columns("campuses")}
    if "created_at" not in campuses_cols:
        op.add_column(
            "campuses",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
        )
    if "updated_at" not in campuses_cols:
        op.add_column(
            "campuses",
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )
    if "name" in campuses_cols:
        col_type = campuses_cols["name"].get("type")
        length = getattr(col_type, "length", None)
        if length != 255:
            op.alter_column(
                "campuses",
                "name",
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=255),
                existing_nullable=False,
            )

    colleges_cols = {col["name"]: col for col in inspector.get_columns("colleges")}
    if "code" not in colleges_cols:
        op.add_column("colleges", sa.Column("code", sa.String(length=50), nullable=False))
    if "created_at" not in colleges_cols:
        op.add_column(
            "colleges",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
        )
    if "updated_at" not in colleges_cols:
        op.add_column(
            "colleges",
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )
    if "name" in colleges_cols:
        col_type = colleges_cols["name"].get("type")
        length = getattr(col_type, "length", None)
        if length != 255:
            op.alter_column(
                "colleges",
                "name",
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=255),
                existing_nullable=False,
            )
    college_uniques = {uc["name"] for uc in inspector.get_unique_constraints("colleges")}
    if None not in college_uniques and "colleges_code_key" not in college_uniques:
        op.create_unique_constraint(None, "colleges", ["code"])

    programs_cols = {col["name"]: col for col in inspector.get_columns("programs")}
    if "campus_id" not in programs_cols:
        op.add_column("programs", sa.Column("campus_id", sa.Integer(), nullable=False))
    program_uniques = {uc["name"] for uc in inspector.get_unique_constraints("programs")}
    if "programs_name_key" in program_uniques:
        op.drop_constraint("programs_name_key", "programs", type_="unique")
    program_fks = {fk["name"] for fk in inspector.get_foreign_keys("programs")}
    if None not in program_fks and "programs_campus_id_fkey" not in program_fks:
        op.create_foreign_key(None, "programs", "campuses", ["campus_id"], ["id"])

    students_cols = {col["name"]: col for col in inspector.get_columns("students")}
    if "program_id" not in students_cols:
        op.add_column("students", sa.Column("program_id", sa.Integer(), nullable=False))
    student_fks = {fk["name"] for fk in inspector.get_foreign_keys("students")}
    if None not in student_fks and "students_program_id_fkey" not in student_fks:
        op.create_foreign_key(None, "students", "programs", ["program_id"], ["id"])
    if "program" in students_cols:
        op.drop_column("students", "program")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    students_cols = {col["name"] for col in inspector.get_columns("students")}
    if "program" not in students_cols:
        op.add_column(
            "students",
            sa.Column(
                "program",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            ),
        )
    student_fks = {fk["name"] for fk in inspector.get_foreign_keys("students")}
    if None in student_fks or "students_program_id_fkey" in student_fks:
        op.drop_constraint(None, "students", type_="foreignkey")
    if "program_id" in students_cols:
        op.drop_column("students", "program_id")

    program_fks = {fk["name"] for fk in inspector.get_foreign_keys("programs")}
    if None in program_fks or "programs_campus_id_fkey" in program_fks:
        op.drop_constraint(None, "programs", type_="foreignkey")
    program_uniques = {uc["name"] for uc in inspector.get_unique_constraints("programs")}
    if "programs_name_key" not in program_uniques:
        op.create_unique_constraint("programs_name_key", "programs", ["name"])
    programs_cols = {col["name"] for col in inspector.get_columns("programs")}
    if "campus_id" in programs_cols:
        op.drop_column("programs", "campus_id")

    college_uniques = {uc["name"] for uc in inspector.get_unique_constraints("colleges")}
    if None in college_uniques or "colleges_code_key" in college_uniques:
        op.drop_constraint(None, "colleges", type_="unique")
    colleges_cols = {col["name"] for col in inspector.get_columns("colleges")}
    op.alter_column(
        "colleges",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    if "updated_at" in colleges_cols:
        op.drop_column("colleges", "updated_at")
    if "created_at" in colleges_cols:
        op.drop_column("colleges", "created_at")
    if "code" in colleges_cols:
        op.drop_column("colleges", "code")

    campuses_cols = {col["name"] for col in inspector.get_columns("campuses")}
    op.alter_column(
        "campuses",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    if "updated_at" in campuses_cols:
        op.drop_column("campuses", "updated_at")
    if "created_at" in campuses_cols:
        op.drop_column("campuses", "created_at")
    op.create_table('signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signatures_pkey')
    )
    op.create_index('ix_signatures_id', 'signatures', ['id'], unique=False)
    # ### end Alembic commands ###
