"""remove college_id from campuses

Revision ID: cfa7a2c1bcb1
Revises: 9b967c8c55a0
Create Date: 2026-03-02 20:12:33.234242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa7a2c1bcb1'
down_revision: Union[str, None] = '9b967c8c55a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campuses_college_id_fkey', 'campuses', type_='foreignkey')
    op.drop_column('campuses', 'college_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campuses', sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('campuses_college_id_fkey', 'campuses', 'colleges', ['college_id'], ['id'])
    # ### end Alembic commands ###
