"""remove college_id from campuses

Revision ID: cfa7a2c1bcb1
Revises: 9b967c8c55a0
Create Date: 2026-03-02 20:12:33.234242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'cfa7a2c1bcb1'
down_revision: Union[str, None] = '9b967c8c55a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    fks = {fk["name"] for fk in inspector.get_foreign_keys("campuses")}
    if "campuses_college_id_fkey" in fks or None in fks:
        op.drop_constraint("campuses_college_id_fkey", "campuses", type_="foreignkey")
    columns = {col["name"] for col in inspector.get_columns("campuses")}
    if "college_id" in columns:
        op.drop_column("campuses", "college_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {col["name"] for col in inspector.get_columns("campuses")}
    if "college_id" not in columns:
        op.add_column(
            "campuses",
            sa.Column(
                "college_id",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            ),
        )
    fks = {fk["name"] for fk in inspector.get_foreign_keys("campuses")}
    if "campuses_college_id_fkey" not in fks and None not in fks:
        op.create_foreign_key(
            "campuses_college_id_fkey",
            "campuses",
            "colleges",
            ["college_id"],
            ["id"],
        )
    # ### end Alembic commands ###
